### ISSUE TITLE
Study the idea to use ansible oc module

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#38]
Since Ansible 2.4, it is possible to use the [oc module](https://docs.ansible.com/ansible/2.4/oc_module.html). Then I propose that we study the idea to use it instead of installing our own `oc` client which is next used by our playbooks. That could resolve the issue on `minishift` where it is more difficult to install a package within the centos or boot2docker image

**Comment by geoand** [comment]
I don't think the `oc` module will be very helpful since we will need to specify the token for each request.
Our current reliance on the `oc` command line tool being installed is probably the easiest way to go
