### ISSUE TITLE
Set necessary label when deploying all-in-one cluster via openshift-ansible

### ISSUE THREAD

**Issue by geoand** [snowdrop/cloud-native-infra#40]
Currently when an all-in-one cluster is deployed via openshift-ansible, Openshift will be able deploy any pods, reporting `0/1 nodes are available: 1 MatchNodeSelector`.

The solution is probably to label the `all-in-one` node

**Comment by cmoulliard** [comment]
ansible var is certainly this one. To be tested

```
openshift_master_node_labels:
  node-role.kubernetes.io/master: 'true'
```

**Comment by cmoulliard** [comment]
We must probably review this sentence defined within the inventory template then

```
[nodes]
192.168.99.50 openshift_node_labels="{'region':'infra','zone':'default'}" openshift_public_hostname=192.168.99.50 openshift_schedulable=true openshift_ip=192.168.99.50
```

**Comment by geoand** [comment]
There seem to be multiple options, I will try them and see :)
