### ISSUE TITLE
Enhance inventory_cloud j2 template to support deployment on openstack vs local, hetzner

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#48]
Enhance inventory_cloud j2 template to support deployment on openstack vs local, hetzner.

A few modifications are required : 

a) openshift_hostname 
openshift_hostname=node_name -> openshift_hostname=ip

Should be good to see if we can also define a hostname for local, hetzner deployments.
If we use the Centos ISO created, then `hostname` command executed on the terminal of the vm returns  : `cloud` and for `hetzner` -> `CentOS-74-64-minimal`
We should perhaps specify it as a name

b) Node, master, etcd

```
[masters]
10.8.250.104 openshift_public_hostname=10.8.250.104 openshift_hostname=172.16.195.12
Change To : -->
192.168.99.50 openshift_public_hostname=192.168.99.50 openshift_ip=192.168.99.50

[etcd]
10.8.250.104
Change To : -->
192.168.99.50 openshift_ip=192.168.99.50

[nodes]
10.8.250.104 openshift_node_labels="{'region':'infra','zone':'default', 'node-role.kubernetes.io/compute': 'true'}" \
   openshift_public_hostname=10.8.250.104 \
   openshift_hostname=172.16.195.12
   
Change To : -->

192.168.99.50 openshift_node_labels="{'region':'infra','zone':'default', 'node-role.kubernetes.io/compute': 'true'}" \
   openshift_public_hostname=192.168.99.50 \
   openshift_ip=192.168.99.50
```

See diff file

![screenshot 2018-04-19 14 04 23](https://user-images.githubusercontent.com/463790/38990450-a00149b2-43da-11e8-979b-90c7b9338657.png)

**Comment by geoand** [comment]
I will update #47 with this
